swagger: "2.0"
info:
  title: "API de Categorias de Despesas"
  description: "Endpoints para gerenciar categorias de despesas"
  version: "1.0.0"
securityDefinitions:
  BearerAuth:
    type: apiKey
    in: header
    name: Authorization
    description: "Utilize o token JWT no formato 'Bearer <token>'"

paths:
  /login:
    post:
      summary: "Login do sistema"
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
                example: "admin"
              password:
                type: string
                example: "senha"
      responses:
        200:
          description: "Login bem-sucedido"
          schema:
            type: object
            properties:
              access_token:
                type: string
                example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        401:
          description: "Credenciais inválidas"
          schema:
            type: object
            properties:
              msg:
                type: string
                example: "Credenciais inválidas"

  /Expense/All:
    get:
      summary: "Recuperar todas as categorias de despesas"
      security:
        - BearerAuth: []
      responses:
        200:
          description: "Lista de categorias"
          schema:
            type: array
            items:
              properties:
                name:
                  type: string

  /Expense:
    post:
      summary: "Criar uma nova categoria de despesa"
      security:
        - BearerAuth: []
      parameters:
        - in: body
          name: body
          required: true
          schema:
            properties:
              name:
                type: string
                example: "Alimentação"
              description:
                type: string
                example: "Alimentação diária"
      responses:
        201:
          description: "Categoria criada com sucesso"

  /BankAccount/All:
    get:
      summary: "Recuperar todas as contas de bancos"
      security:
        - BearerAuth: []
      responses:
        200:
          description: "Lista de bancos"
          schema:
            type: array
            items:
              properties:
                name:
                  type: string

  /BankAccount:
    post:
      summary: "Criar uma nova conta bancária"
      security:
        - BearerAuth: []
      parameters:
        - in: body
          name: body
          required: true
          schema:
            properties:
              bank_name:
                type: string
                example: "Banco do Brasil"
              account_number:
                type: string
                example: "Numero da conta"
              balance:
                type: float
                example: "Conta para despesas gerais"
      responses:
        201:
          description: "Conta bancária criada com sucesso"
